Add LIP "Introduce Fee module"
LiskHQ/lips pull request #101
Opened 2021-09-01 10:32 UTC by MaximeGagnebin

2021-09-01 11:36 UTC, ManuGowda approved these changes

2021-09-01 13:01 UTC, IkerAlus approved these changes
Looks all good.

2021-09-06 07:26 UTC, ricott1 requested changes
small last typo, the rest LGTM

2021-09-06 07:26 UTC, ricott1 commented on proposals/lip-Introduce_Fee_module.md
> +The fee module does not store information in the state.
```suggestion
The Fee module does not store information in the state.
```

2021-09-06 07:28 UTC, ricott1 approved these changes
LGTM

2021-09-14 10:53 UTC, mitsuaki-u approved these changes

2021-09-24 13:57 UTC, karmacoma approved these changes

2021-09-24 13:58 UTC, merged