Update lip 0063 according to Legacy module migration logic
LiskHQ/lips pull request #152
Opened 2022-06-10 13:10 UTC by sergeyshemyakov

2022-06-10 14:31 UTC, MaximeGagnebin requested changes
I think the logic for handling the amounts for legacy accounts should be revisited.

2022-06-10 14:31 UTC, MaximeGagnebin commented on proposals/lip-0063.md
>  ```
I think this logic is not really following the migration paradigm.
The migration should not mint + lock tokens. This amount should be  added to the `assets` entry for the token module under the correct address.

2022-06-10 15:18 UTC, janhack requested changes
Ah, I missed the context here. We are actually just computing the genesis block and therefore cannot call any APIs or make any state changes. As Maxime noted, we would need to modify the asset of the Token module instead.

2022-06-13 10:44 UTC, sameersubudhi approved these changes
LGTM 👍

2022-06-13 11:24 UTC, MaximeGagnebin approved these changes
According to the current specs, I think the different asset arrays need to be sorted (each module defines the sorting to be respected)
I would approve the PR as I think the Legacy module change is now settled.

2022-06-21 12:34 UTC, janhack requested changes
I think there is an issue with the current specifications if `ADDRESS_LEGACY_RESERVE` has any balance.

2022-06-28 14:57 UTC, janhack approved these changes
Looks all good now!

2022-07-22 13:09 UTC, karmacoma approved these changes

2022-07-22 13:09 UTC, merged