Update LIP0027
LiskHQ/lips pull request #154
Opened 2022-06-17 11:48 UTC by ricott1

2022-06-17 13:02 UTC, ricott1 commented on proposals/lip-0027.md
> +**Superseded in [LIP 0064]([)https://github.com/LiskHQ/lips/blob/main/proposals/lip-0064.md)**: LIP 0064 requires that every property is _required_. Therefore, valid binary messages cannot have missi
```suggestion
**Superseded in [LIP 0064](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0064.md)**: LIP 0064 requires that every property is _required_. Therefore, valid binary messages cannot have missing values, except for properties of type array where the missing value corresponds to the empty array, and valid messages cannot have missing properties. This implies `encode(decode( binaryMsg )) == binaryMsg` for every valid binary message `binaryMsg` and `decode(encode( msg )) == msg` for every valid message `msg`. Hence, no special care must be taken anymore.
```

2022-06-17 13:02 UTC, ricott1 commented on proposals/lip-0027.md
> +**Superseded in [LIP 0064]([)https://github.com/LiskHQ/lips/blob/main/proposals/lip-0064.md)**: LIP 0064 requires additionally that every schema of type _object_ must use the `required` keyword, and
```suggestion
**Superseded in [LIP 0064](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0064.md)**: LIP 0064 requires additionally that every schema of type _object_ must use the `required` keyword, and every property of the object must be contained its value.
```

2022-06-21 11:35 UTC, janhack commented on proposals/lip-0027.md
> +1. Missing values: Whenever a binary message does not contain a specific field, the corresponding field in the parsed object is set to its default value. The default value is type-specific:
I think here we want to have a nested list. The markdown output is just a regular list, however. Maybe the indentation needs to be changed.

2022-06-21 11:41 UTC, janhack requested changes
There is one minor issue with a nested list.

Overall, I think we should avoid cosmetic formatting changes of past LIPs and only focus on the necessary changes (i.e., reference to LIP 64 in this case).

2022-06-21 11:55 UTC, janhack approved these changes

2022-06-21 18:53 UTC, gkoumout approved these changes
Looks good to me!

2022-06-23 12:26 UTC, karmacoma approved these changes

2022-06-23 12:26 UTC, merged