Add LIP: "Update Lisk SDK modular blockchain architecture"
LiskHQ/lips pull request #164
Opened 2022-08-09 15:30 UTC by shuse2

### Description
Proposing informational LIP to describe Lisk SDK v6 architecture and terminologies used

2022-08-11 16:45 UTC, janhack commented on proposals/lip-update_lisk_sdk_modular_architecture.md
> +Author: Shusetsu Toda <shusetsu@lightcurve.io>
The following line is missing:
```
Discussions-To: https://research.lisk.com/t/update-lisk-sdk-modular-blockchain-architecture/343
```

2022-08-11 16:46 UTC, janhack requested changes
The file header should be updated with the link to the research forum. Otherwise, it looks all good.

2022-08-12 07:34 UTC, ricott1 commented on proposals/lip-update_lisk_sdk_modular_architecture.md
> +## Reference Implementation
Should we just drop this section?

2022-08-12 07:43 UTC, ricott1 approved these changes

2022-08-12 09:12 UTC, janhack approved these changes
Looks all good!

2022-08-22 13:11 UTC, ishantiw approved these changes

2022-09-01 10:00 UTC, karmacoma approved these changes

2022-09-01 10:01 UTC, merged