Update LIP 0055
LiskHQ/lips pull request #166
Opened 2022-08-16 09:57 UTC by ricott1

2022-08-17 13:49 UTC, janhack commented on proposals/lip-0055.md
> +Furthermore, we update the block header schema to include new properties introduced by [LIP 0040][lip-0040], [LIP 0058][lip-0058], [LIP 0061][lip-0061], and [LIP "Introduce events and event root"][li
```suggestion
Furthermore, we update the block header schema to include new properties introduced by [LIP 0040][lip-0040], [LIP 0058][lip-0058], [LIP 0061][lip-0061], and [LIP 0065][lip-0065].
```

2022-08-17 13:49 UTC, janhack commented on proposals/lip-0055.md
> +- `eventRoot`: The root of the sparse Merkle tree that is computed from the events emitted during the block processing. See [LIP "Introduce events and event root"][lip-0065] LIP for the reason why it
```suggestion
- `eventRoot`: The root of the sparse Merkle tree that is computed from the events emitted during the block processing. See [LIP 0065][lip-0065] LIP for the reason why it needs to be included in a block header.
```

2022-08-17 13:49 UTC, janhack commented on proposals/lip-0055.md
> +Here, the function `eventRoot` calculates the events root of the block with the input height as specified in [LIP "Introduce events and event root"][lip-0065].
```suggestion
Here, the function `eventRoot` calculates the events root of the block with the input height as specified in [LIP 0065][lip-0065].
```

2022-08-17 13:58 UTC, janhack approved these changes
Just some cosmetic suggestions, otherwise looks good.

2022-08-18 11:25 UTC, sergeyshemyakov approved these changes
Looks good to me

2022-08-22 09:42 UTC, janhack commented on proposals/lip-0055.md
> +  serializedBlockHeader encode(blockHeaderSchema, block.header)
```suggestion
  serializedBlockHeader = encode(blockHeaderSchema, block.header)
```

2022-08-22 09:43 UTC, janhack commented on proposals/lip-0055.md
> +  serializedUnsignedBlockHeader encode(unsignedBlockHeaderSchema, block.header)
```suggestion
  serializedUnsignedBlockHeader = encode(unsignedBlockHeaderSchema, block.header)
```

2022-08-22 09:44 UTC, janhack requested changes
I left a suggestion for two small typos.

2022-08-22 09:46 UTC, janhack approved these changes
Looks all good.

2022-09-01 09:11 UTC, karmacoma approved these changes

2022-09-01 09:11 UTC, merged