Improve definition of CHAIN_ID_MAINCHAIN and TOKEN_ID_LSK
LiskHQ/lips pull request #190
Opened 2022-11-21 11:02 UTC by AndreasKendziorra

This PR improves the definition of the constants `CHAIN_ID_MAINCHAIN` and `TOKEN_ID_LSK` in several LIPs by:
- Defining `CHAIN_ID_MAINCHAIN = CHAIN_ID_PREFIX + 0x 00 00 00` in LIP 0063 (Mainchain migration and configuration) where it is mentioned that `CHAIN_ID_PREFIX` depends on the network.
- Every LIP that uses `CHAIN_ID_MAINCHAIN` uses the same definition and refers to LIP 0063.
- Defining `TOKEN_ID_LSK = CHAIN_ID_MAINCHAIN +  0x 00 00 00 00` in LIP 0051 (Token module).
- Every LIP that uses `TOKEN_ID_LSK` uses the same definition and refers to LIP 0051.
- Unify the constants names and remove alternatives like `MAINCHAIN_ID` or `TOKEN_ID_LSK_MAINCHAIN`.

Note that many LIPs have an individual style to list and define constants. Therefore, the changes are not consistent in order to be as close as possible to the current style of each LIP.

2022-11-21 11:09 UTC, ricott1 commented on proposals/lip-0042.md
> +| `TOKEN_ID_LSK`                  | bytes    | as specified in [LIP 0051](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#constants-and-notations) |
```suggestion
| `TOKEN_ID_LSK`                  | bytes    | specified in [LIP 0051](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#constants-and-notations) |
```

2022-11-21 11:09 UTC, ricott1 commented on proposals/lip-0042.md
> +| `TOKEN_ID_LSK`                  | bytes    | as specified in [LIP 0051](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#constants-and-notations) |
just for consistency with line above

2022-11-21 11:11 UTC, ricott1 commented on proposals/lip-0045.md
> +| `TOKEN_ID_LSK` | bytes | `CHAIN_ID_MAINCHAIN` +  0x00000000 | The token ID of the Lisk token. Defined in the Token module. |
Why do we specify the value here rather than linking to LIP51 like we do in other LIPs?

2022-11-21 11:12 UTC, ricott1 requested changes
Very minor comments

2023-01-13 17:37 UTC, janhack commented
We close the PR in favor of https://github.com/LiskHQ/lips/pull/205.

2023-01-13 17:37 UTC, closed without merging