Small corrections
LiskHQ/lips pull request #203
Opened 2023-01-11 09:12 UTC by mjerkov

Updated according to comments for LIP0048 on [Trello card](https://trello.com/c/RqoOpXeM/1432-small-issues-in-lips):

- It uses b.generatorPublicKey in line 235 instead of b.header.generatorAddress.
- There are two events in the LIP, but in the constants table there is just one event.
- The type CCM is used but not defined.

Comment: No problem with events was found - there are three events and all of them are mentioned in the Constants table.

2023-01-11 11:43 UTC, sergeyshemyakov approved these changes
Good catch with `=` in schemas! Also judging from the git history, the events were fixed by Maxime sometime in December.
Just one remark from my side: make sure that the link works before merging.

2023-01-11 11:43 UTC, sergeyshemyakov commented on proposals/lip-0048.md
> +| `CCM`         | object | Must follow the `crossChainMessageSchema` schema defined in [LIP 0049](lip-0049#ccmschema).
The link to the schema is broken. I suspect that `()` should be changed into `[]`. 
It looks like the link is resolved into the relative path `/lip-0049` from the location of the file, which is interesting.

2023-01-11 14:03 UTC, gkoumout requested changes
Good job Miroslav! I just caught one inconsistency which was here even before but we had not noticed, plz have a look.

2023-01-11 16:08 UTC, mjerkov commented on proposals/lip-0048.md
> +| Name          | Type   | Validation
Thanks for noticing this! Definitely something to be corrected (please check the next commit).

2023-01-11 16:15 UTC, gkoumout approved these changes
Approved, just mentioned a small typo. Bravo!

2023-01-11 16:15 UTC, gkoumout commented on proposals/lip-0048.md
> +We use the definition of the following type:
```suggestion
We use the definition of the following types:
```

2023-01-11 16:17 UTC, mjerkov commented on proposals/lip-0048.md
> +We use the definition of the following type:
Thanks again, my mistake this time :)!

2023-01-13 11:21 UTC, karmacoma approved these changes

2023-01-13 11:22 UTC, merged