Fixing floating point arithmetic
LiskHQ/lips pull request #229
Opened 2023-01-20 11:23 UTC by AnanyaSshri

This PR fixes the usage of floating point arithmetic in LIPs by replacing `floor` or `ceil` with the following:

- `floor(x / y )` is replaced with `x // y`
- `ceil(x / y)` is replaced with `(x + y -1) // y`

where // is the integer division.

2023-01-20 12:50 UTC, vjaiman approved these changes
Looks good.

2023-01-23 10:07 UTC, janhack commented on proposals/lip-0038.md
> +    aggregationBits = byte string of length ((length(keysList)+8-1) //8) with all bytes set to 0
```suggestion
    aggregationBits = byte string of length (length(keysList) + 7)  // 8 with all bytes set to 0
```

2023-01-23 10:08 UTC, janhack commented on proposals/lip-0047.md
> +     * Minimum value: (`totalWeight` // 3) + 1, where // is the integer division.
```suggestion
     * Minimum value: `totalWeight // 3 + 1`, where // is the integer division.
```

2023-01-23 10:09 UTC, janhack commented on proposals/lip-0058.md
> +If `aggregateBFTWeight` is the sum of BFT weights of all validators stored, then the value of this property must satisfy `(aggregateBFTWeight // 3)+1 <= precommitThreshold <= aggregateBFTWeight`.
```suggestion
If `aggregateBFTWeight` is the sum of BFT weights of all validators stored, then the value of this property must satisfy `(aggregateBFTWeight // 3) + 1 <= precommitThreshold <= aggregateBFTWeight`.
```

2023-01-23 10:09 UTC, janhack commented on proposals/lip-0058.md
> +If `aggregateBFTWeight` is the sum of BFT weights of all validators stored, then the value of this property must satisfy `(aggregateBFTWeight // 3)+1 <= certificateThreshold <= aggregateBFTWeight.`
```suggestion
If `aggregateBFTWeight` is the sum of BFT weights of all validators stored, then the value of this property must satisfy `(aggregateBFTWeight // 3) + 1 <= certificateThreshold <= aggregateBFTWeight.`
```

2023-01-23 10:11 UTC, janhack commented on proposals/lip-0063.md
> +    r = ((a.header.height - HEIGHT_PREVIOUS_SNAPSHOT_BLOCK) + ROUND_LENGTH - 1) // ROUND_LENGTH
As it is not obvious that this expression computes the ceiling, I would introduce a dedicated function for it similar to LIP 57 https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md#ceiling.

2023-01-23 10:17 UTC, janhack commented on proposals/lip-0038.md
> +    aggregationBits = byte string of length ((length(keysList)+8-1) //8) with all bytes set to 0
Also consider adding a dedicated function for `ceiling` similar to LIP 57 https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md#ceiling.

2023-01-24 13:06 UTC, vjaiman approved these changes
Looks good.

2023-01-25 08:43 UTC, janhack commented on proposals/lip-0038.md
> +
In general, the internal function section only is used in LIPs defining a module. In this LIP here anything could be considered an internal function as it defines rather a library. Therefore, I would maybe rename the section to "Auxiliary Function". 

Further note that the rationale can before or after the specifications. The function should be defined in the specification section though.

2023-01-26 08:12 UTC, AnanyaSshri commented on proposals/lip-0038.md
> +
Renamed it as per the suggestion.

2023-01-26 08:12 UTC, AnanyaSshri commented on proposals/lip-0063.md
> +```
Renamed it as per the suggestion.

2023-01-30 09:43 UTC, janhack commented on proposals/lip-0063.md
> +    r = ceiling((a.header.height - HEIGHT_PREVIOUS_SNAPSHOT_BLOCK), ROUND_LENGTH)
```suggestion
    r = ceiling(a.header.height - HEIGHT_PREVIOUS_SNAPSHOT_BLOCK, ROUND_LENGTH)
```

2023-01-30 09:46 UTC, janhack commented on proposals/lip-0058.md
> +* `prevoteThreshold`: This property stores the prevote threshold. For casting a precommit for a block, the sum of BFT weights of all validators casting a prevote for this block has to be at least the
```suggestion
* `prevoteThreshold`: This property stores the prevote threshold. For casting a precommit for a block, the sum of BFT weights of all validators casting a prevote for this block has to be at least the prevote threshold. If `aggregateBFTWeight` is the sum of BFT weights of all validators stored, then the property value must be `((2 * aggregateBFTWeight(h)) // 3) + 1`.
```

2023-01-30 09:46 UTC, janhack commented on proposals/lip-0058.md
> +* `prevoteThreshold`: This property stores the prevote threshold. For casting a precommit for a block, the sum of BFT weights of all validators casting a prevote for this block has to be at least the
Here the order of operations could matter.

2023-01-30 09:46 UTC, janhack commented on proposals/lip-0063.md
> +    r = ceiling((a.header.height - HEIGHT_PREVIOUS_SNAPSHOT_BLOCK), ROUND_LENGTH)
Brackets around one input parameter of a function are not needed.

2023-01-30 09:47 UTC, janhack requested changes
I added two minor suggestions.

2023-01-30 15:06 UTC, janhack approved these changes

2023-01-30 15:10 UTC, merged