Add LIP: "Introduce direct sidechain channels"
LiskHQ/lips pull request #374
Opened 2023-06-07 11:34 UTC by ricott1

2023-06-07 11:45 UTC, AndreasKendziorra requested changes

2023-06-07 11:45 UTC, AndreasKendziorra commented on proposals/lip-introduce-direct-sidechain-channels.md
> +This LIP introduces one new command that extend the standard interoperability protocol and allows sidechains to register direct channels, enabling them to exchange cross-chain messages directly witho
```suggestion
This LIP introduces one new command that extends the standard interoperability protocol and allows sidechains to register direct channels, enabling them to exchange cross-chain messages directly without routing them via the mainchain.
```

2023-06-07 12:05 UTC, AndreasKendziorra approved these changes

2023-06-07 12:21 UTC, gkoumout approved these changes

2023-06-22 15:34 UTC, vjaiman approved these changes

2023-06-22 15:34 UTC, merged