Update LIP 0057 - change bft capping value
LiskHQ/lips pull request #377
Opened 2023-06-07 14:56 UTC by gkoumout

This PR fixes issue #376.

2023-06-08 06:59 UTC, ricott1 commented on proposals/lip-0057.md
>  Note that further we choose `floor(2/3 * aggregateBFTWeight) + 1` as precommit and certificate threshold for PoS chains, see [LIP 0058][lip-0058] for an explanation of these parameters. Here `aggrega
```suggestion
Note that further we choose `floor(2/3 * aggregateBFTWeight) + 1` as precommit and certificate threshold for PoS chains, see [LIP 0058][lip-0058] for an explanation of these parameters. Here `aggregateBFTWeight` is the sum of BFT weights of the active validators. This choice of BFT parameters means that the safety and liveness of the BFT consensus protocol is ensured if `<1/3 * aggregateBFTWeight` is malicious (for the case of changing validators the guarantees are slightly weaker). The capping of BFT weights to 10 % for the Lisk mainchain implies that at least 7 validators would need to be malicious as any set of 6 validators would have `<1/3 * aggregateBFTWeight` BFT weight. Similarly, only a set of at least 14 validators could have BFT weight of `>= floor(2/3 * aggregateBFTWeight) + 1` and would therefore be able to generate any certificate. Hence, the capping ensures a minimum of decentralization in the validator set, even in the case of very unbalanced validator weight distribution. In practice, we expect the capping to only effect very few validators, in particular, as rewards are also distributed proportional to the BFT weights.
```

2023-06-08 06:59 UTC, ricott1 commented on proposals/lip-0057.md
>  Note that further we choose `floor(2/3 * aggregateBFTWeight) + 1` as precommit and certificate threshold for PoS chains, see [LIP 0058][lip-0058] for an explanation of these parameters. Here `aggrega
Also the rationale about the number of nodes must be updated.

2023-06-08 07:00 UTC, ricott1 requested changes
We need to update the rationale about the capping limit on mainchain plus one leftover 5%

2023-06-08 07:15 UTC, ricott1 approved these changes

2023-06-08 08:54 UTC, ishantiw approved these changes

2023-06-08 16:20 UTC, janhack approved these changes
Looks good.

Could we still link an issue for updating the implementation?

2023-06-08 16:36 UTC, ishantiw commented
Related SDK issue https://github.com/LiskHQ/lisk-sdk/issues/8567

2023-06-09 11:29 UTC, janhack approved these changes
Editorial approval

2023-06-09 11:30 UTC, merged