remove call to isLive
LiskHQ/lips pull request #390
Opened 2023-06-26 12:42 UTC by gkoumout

This PR fixes #389 .

2023-06-26 12:44 UTC, ricott1 approved these changes

2023-06-26 13:11 UTC, mitsuaki-u approved these changes

2023-06-26 14:07 UTC, mitsuaki-u requested changes
I would also add `timestamp` as a parameter since `isLive` called in the mainchain portion still requires it

2023-06-26 14:22 UTC, mitsuaki-u approved these changes

2023-06-27 12:24 UTC, AndreasKendziorra approved these changes

2023-07-03 12:50 UTC, janhack approved these changes
Editorial approval

2023-07-03 12:50 UTC, merged