Update constant recovered value for state recovery command
LiskHQ/lips pull request #434
Opened 2023-08-01 10:57 UTC by ricott1

Closes https://github.com/LiskHQ/lips/issues/433.

2023-08-02 07:46 UTC, AnanyaSshri approved these changes

2023-08-02 08:17 UTC, janhack commented on proposals/lip-0045.md
> +| `RECOVERED_STORE_VALUE` | bytes | `\x00 * 32` | The constant value used for recovered entries of the state recovery command. Since there is no known sha256 pre-image for this constant, the same sto
You are not using an apostrophe here. Further, I would suggest using the same notation as in other LIPs, e.g., LIP 63.

2023-08-02 08:20 UTC, janhack requested changes
One small comment.

2023-08-02 08:51 UTC, janhack approved these changes

2023-08-07 13:49 UTC, mitsuaki-u approved these changes

2023-08-08 11:17 UTC, janhack approved these changes
Editorial approval

2023-08-08 11:17 UTC, merged