Compute index/position in Merkle tree correctly
LiskHQ/lips pull request #445
Opened 2023-08-11 08:04 UTC by AndreasKendziorra

Fixes #444

2023-08-11 10:06 UTC, ricott1 approved these changes

2023-08-11 11:29 UTC, gkoumout approved these changes

2023-08-15 13:18 UTC, sergeyshemyakov approved these changes
Looks good

2023-08-16 12:16 UTC, mitsuaki-u approved these changes

2023-08-17 10:06 UTC, sergeyshemyakov requested changes

2023-08-17 10:06 UTC, sergeyshemyakov commented on proposals/lip-0054.md
> +    if idxs[0] > 1:
I think it should be `if idxs[0] <= 1`.

2023-08-17 10:09 UTC, AndreasKendziorra commented on proposals/lip-0054.md
> +    if idxs[0] > 1:
right :) I fixed it

2023-08-17 10:11 UTC, sergeyshemyakov approved these changes
Looks good

2023-08-17 10:23 UTC, gkoumout approved these changes

2023-08-17 12:27 UTC, mitsuaki-u approved these changes

2023-08-17 15:40 UTC, janhack approved these changes
Editorial approval

2023-08-17 15:40 UTC, merged