Address PoA audit code quality issues
LiskHQ/lips pull request #482
Opened 2023-09-12 12:09 UTC by sergeyshemyakov

Resolve https://github.com/LiskHQ/lips/issues/481

2023-09-13 07:38 UTC, vjaiman approved these changes
Looks good to me.

2023-09-14 10:13 UTC, gkoumout requested changes

2023-09-14 10:13 UTC, gkoumout commented on proposals/lip-0047.md
> +        nextValidators  = PoS.shuffleValidatorsList(snapshotStore(0).validators, randomSeed)
I find this an undesirable dependency: the idea is that chains should use PoA OR PoS, so it does not make much sense IMO to call a PoS endpoint from PoA module. 

Perhaps the best would be if we move the `shuffleValidatorsList` to random module, but I need to think a bit about it.

2023-09-15 09:37 UTC, mitsuaki-u approved these changes

2023-09-19 12:55 UTC, gkoumout requested changes

2023-09-21 16:13 UTC, janhack commented on proposals/lip-0047.md
> +The function reorders and returns the list of validators as specified in [LIP 0003][lip-0003#specs]. It must be implemented exactly as the `shuffleValidatorsList` function in the [PoS module](https:/
```suggestion
The function reorders and returns the list of validators. It must be implemented exactly as the `shuffleValidatorsList` function in the [PoS module](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md#shufflevalidatorslist).
```

2023-09-21 16:14 UTC, janhack commented on proposals/lip-0047.md
> +The function reorders and returns the list of validators as specified in [LIP 0003][lip-0003#specs]. It must be implemented exactly as the `shuffleValidatorsList` function in the [PoS module](https:/
```suggestion
The function reorders and returns the list of validators. It must be implemented exactly as the `shuffleValidatorsList` function in the [PoS module](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md#shufflevalidatorslist).
```

2023-09-21 16:15 UTC, janhack commented on proposals/lip-0047.md
> +The function reorders and returns the list of validators as specified in [LIP 0003][lip-0003#specs]. It must be implemented exactly as the `shuffleValidatorsList` function in the [PoS module](https:/
I think the historic reference to LIP 0003 is not important here and rather confusing (there should be one source of truth for the specifications).

2023-09-21 16:18 UTC, janhack requested changes
Looks good, I just left one suggestion.

2023-09-21 16:25 UTC, gkoumout approved these changes

2023-09-21 16:36 UTC, janhack approved these changes
Editorial approval

2023-09-21 16:36 UTC, merged