Introduce function to set thresholds in PoS module
LiskHQ/lips pull request #489
Opened 2023-09-25 22:08 UTC by gkoumout

The purpose of this PR is to refactor the PoS module so that there exists a single function `computeThresholds` to determine the precommit and certificate thresholds required for BFT and interoperability respectively. 

This way, at all stages when those thresholds need to get updated, this would be done via calling `computeThresholds`. As a consequence, sidechain developers could modify the logic on computing those thresholds by just modifying this function instead of having to check all places where those thresholds are updated.

2023-09-26 07:37 UTC, ricott1 approved these changes

2023-09-27 08:32 UTC, janhack requested changes
Looks good. I just have two cosmetic remarks.

2023-09-27 08:32 UTC, janhack commented on proposals/lip-0057.md
> +This function sets the precommit and certificate thresholds that are forwarded to the consensus layer, see [LIP 0058][lip-0058] for details.
```suggestion
This function computes the precommit and certificate thresholds that are forwarded to the consensus layer, see [LIP 0058][lip-0058] for details. 
```

2023-09-27 08:32 UTC, janhack commented on proposals/lip-0057.md
> +Note that further we choose `floor(2/3 * aggregateBFTWeight) + 1` as precommit and certificate threshold for PoS chains, see [LIP 0058][lip-0058] for an explanation of these parameters. Here `aggrega
```suggestion
Note that further we choose `floor(2/3 * aggregateBFTWeight) + 1` as precommit and certificate threshold for PoS chains, see [LIP 0058][lip-0058] for an explanation of these parameters. Here `aggregateBFTWeight` is the sum of BFT weights of the active validators. This choice of BFT parameters means that the safety and liveness of the BFT consensus protocol is ensured if `<1/3 * aggregateBFTWeight` is malicious (for the case of changing validators the guarantees are slightly weaker). Developers might choose to modify the threshold values for their sidechains by updating the [`computeThresholds` function](#computethresholds). We crucially note, however, that modifying the chosen parameters has consequences for the security guarantees of the chain according to the security-liveness tradeoff proven in Theorem 4.4 of the [Lisk-BFT paper][lisk-bft-paper]. Therefore, we highly recommend not updating those parameters, unless the tradeoff is well-understood and there is some very clear reason to do so for a specific chain.
```

2023-09-28 07:20 UTC, janhack approved these changes
Editorial approval

2023-09-28 07:20 UTC, merged