add LIP "Introduce sparse Merkle trees"
LiskHQ/lips pull request #86
Opened 2021-05-26 13:29 UTC by ricott1

2021-05-26 14:55 UTC, IkerAlus approved these changes
All looks good to me, great work.

2021-05-31 07:40 UTC, shuse2 approved these changes

2021-06-01 08:51 UTC, janhack commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +```
As we have the table of constants, lines 123-129 are redundant.

2021-06-01 14:04 UTC, janhack commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +| KEY_LENGTH    | integer | Set when initializing the data structure |
Here an below it is not clear what unit is used for the key length.

Maybe the parameter name could be `KEY_LENGTH_BYTES` or something similar. An for the description here we could as "Length of the key in bytes."

2021-06-01 15:05 UTC, janhack commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +    return response
The indentation above is incorrect.

2021-06-01 15:46 UTC, janhack commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +        let binaryQueryKey=binaryExpansion(q.key)
As query key I would understand the key provided in the query. Maybe proof key would be a better name here?

2021-06-01 15:47 UTC, janhack requested changes
I left a few minor comments.

2021-06-02 08:46 UTC, ricott1 commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +    return response
fixed

2021-06-04 05:55 UTC, Incede requested changes

2021-06-04 05:55 UTC, Incede commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +    *   The Prover finds the leaf node corresponding to each key `k` in `queryKeys` and assigns to each a `query` object with a key, a bitmap, and a value. The bitmap indicates the presence of defaul
```suggestion
    *   The Prover finds the leaf node corresponding to each key `k` in `queryKeys` and assigns to each a `query` object with a key, a bitmap, and a value. The bitmap indicates the presence of default empty nodes along the path to the Merkle root. If the node exists, `query.key` is set to `k` and `query.value` to the node value; if the node does not exist, the Prover returns an inclusion proof for another leaf or a default empty node in the path of the `k`. In this case, `query.key` and `query.value` are set to the leaf key and leaf value or to `k` and empty value, respectively.  
```

2021-06-04 11:27 UTC, janhack commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +        let binaryQueryKey=binaryExpansion(q.key)
Looks good. That is more clear.

2021-06-04 11:27 UTC, janhack approved these changes

2021-06-04 11:46 UTC, ricott1 commented on proposals/lip-Introduce-sparse-Merkle-trees.md
> +    *   The Prover finds the leaf node corresponding to each key `k` in `queryKeys` and assigns to each a `query` object with a key, a bitmap, and a value. The bitmap indicates the presence of defaul
nice catch! thanks

2021-06-04 11:49 UTC, Incede approved these changes

2021-06-08 13:41 UTC, karmacoma approved these changes

2021-06-08 13:41 UTC, merged