Update status and reference implementation
LiskHQ/lips pull request #99
Opened 2021-08-26 12:49 UTC by shuse2

### Update status
- lip-0005
- lip-0006
- lip-0011

Update status of above lips to `Obsolete`

### Update reference implementation
- lip-0013
- lip-0014
- lip-0015
- lip-0016
- lip-0017
- lip-0021
- lip-0022
- lip-0023
- lip-0024
- lip-0025
- lip-0026
- lip-0035
- lip-0036

Update Reference implementation of above LIPs

2021-08-30 09:25 UTC, janhack commented on proposals/lip-0021.md
>  ## Reference Implementation
This LIP is withdrawn and was never implemented.

2021-08-30 09:28 UTC, janhack commented on proposals/lip-0024.md
> +[Add fail safe delegate banning mechanism](https://github.com/LiskHQ/lisk-sdk/issues/5058)
I did not have a closer look, but it seems like the implementation you link is mainly about productivity banning, which was already part of LIP 0023, and not about the PoM transaction defined in this LIP.

2021-08-30 09:30 UTC, janhack commented on proposals/lip-0013.md
> +## Reference Implementation
There is already a section "Reference Implementation" in this LIP.

2021-08-30 09:37 UTC, janhack requested changes
I left some minor comments. I think it would be nice if you could also add the "Reference Implementation" section to the "template.md" file in the root directory. This way we also have this consistent structure in the template.

2021-08-30 13:34 UTC, janhack approved these changes
Looks good.

2021-09-07 13:57 UTC, karmacoma approved these changes

2021-09-07 13:57 UTC, merged